# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dai-industry-admin

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://daistrapi.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_565db741e79d4a8e9f37c40e3328776f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d470e3ab9e664251bf957f2fd6511a69 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: daistrapi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_565db741e79d4a8e9f37c40e3328776f }}/dai-form-site-docker:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dai-industry-admin'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2116d905bd434918b2cc33a569fb25f7 }}
        images: 'daistrapi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_565db741e79d4a8e9f37c40e3328776f }}/dai-form-site-docker:${{ github.sha }}'